### ISSUE TITLE
General changes

### ISSUE THREAD

**Issue by aayushbrahmbhatt** [aayushbrahmbhatt/Simplii#6]
1. Add proper README file
2. Cover more test cases 
3. Resolve bug present in the YML file

**Comment by Tanay27102002** [comment]
working on the following issues!

**Comment by naisargshah** [comment]
Is the issues resolved now tanay?

**Comment by Tanay27102002** [comment]
almost done raising an PR in 2hrs

**Comment by Tanay27102002** [comment]
Proper readme files have been updated and and yml bugs have been resolved the tests are still in progress closing the issues.

**Comment by Tanay27102002** [comment]
issue resolved
